server:
  port: 8081


spring:
  thymeleaf:
    cache: false # \u5173\u95ED\u9875\u9762\u7F13\u5B58
    encoding: UTF-8 # \u6A21\u677F\u7F16\u7801
    prefix: classpath:/templates/  # \u9875\u9762\u6620\u5C04\u8DEF\u5F84
    suffix: .html # \u8BD5\u56FE\u540E\u7684\u540E\u7F00
    mode: HTML5 # \u6A21\u677F\u6A21\u5F0F

    #\u6570\u636E\u6E90\u914D\u7F6E
  datasource:
    url: jdbc:mysql://localhost:3306/sta_job?serverTimezone=GMT
    username: root
    password: tiger
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:mapper/*.xml   # mapper\u6620\u5C04\u6587\u4EF6
  type-aliases-package: com.fh.entity #\u626B\u63CFmodel\u5305 \u4F7F\u7528\u522B\u540D




